---
title: "pictogram for decision tool"
author: "Sachin Shah"
date: "9/1/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(hrbrthemes)
library(waffle)
library(extrafont)
library(dplyr)

## modify plot theme
mod.theme <-theme_ipsum_rc(base_family = "Arial", 
                           plot_title_margin = 0,
                           subtitle_family = "Arial",
                           subtitle_size = 10,
                           subtitle_margin = 0,
                           caption_margin = 0,
                           grid="",
                           plot_margin = margin(0, 0, 0, 0),
                           panel_spacing = grid::unit(0, "lines"),) +
  theme_enhance_waffle() +
  theme(legend.position = "none")
  theme(legend.text = element_text(size = 14, hjust = 0, vjust = 0))
  
## set common variables 
# size of icon 
  picto.size <- 9


```

#
```{r mayobase}

#names
  picto.names <- c("No event", "Stroke", "Censor", "Death")
  
## ADL


custom.color <- c("tomato", "#8037A8", "black", "#559DB5")
picto.size <- 9

tibble(
  event = factor(
    picto.names, 
    levels=picto.names
    ),
  py = c(9, 4, 5, 0)
) -> xdf
xdf

fig.mayobase<- 
  ggplot(
    xdf, 
    aes(label = event, 
        values = py, 
        color = event)) +
  geom_pictogram(
    n_rows = 5, 
    make_proportional = F, 
    size = picto.size
    ) +
  scale_color_manual( name = NULL, values = custom.color) +
  scale_label_pictogram(name = NULL, values = c("female", "female", "female")) +
  coord_equal() +
  mod.theme 

fig.mayobase
ggsave("/Users/sjs73/Dropbox (Personal)/R - Projects/Talks/BMC/base.png", fig.mayobase, width = 5, height = 5)
```

## Future state

```{r future state with}

#names
  picto.names <- c("Alive and well", "Disabled", "Deceased")
  
## ADL
tibble(
  disability = factor(picto.names,levels=picto.names),
  py = c(35, 25, 40)
) -> xdf

custom.color <- c("#75A8FF", "#FF8076", "#373D3F")

xdf

fig.future.with<- ggplot(xdf, aes(label = disability, values = py, color = disability)) +
  geom_pictogram(n_rows = 10, make_proportional = F, size = picto.size) +
  scale_color_manual( name = NULL, values = custom.color) +
  scale_label_pictogram(name = NULL, values = c(Fruit = "female", Sandwiches = "female", Pizza = "female")) +
  coord_equal() +
  mod.theme + 
  theme(legend.position = "bottom") +
  theme(legend.key.height = unit(0.25, "line")) +
  theme(legend.text = element_text(size = 10, hjust = 0, vjust = .95)) 


fig.future.with
ggsave("/Users/sachinshah/Dropbox/Research - Projects/WIP/future_with.png", fig.future.with, width = 5, height = 5)
```

````{r future state without}
#names
  picto.names <- c("Alive and well", "Disabled", "Deceased")
  
## ADL
tibble(
  disability = factor(picto.names,levels=picto.names),
  py = c(32, 28, 40)
) -> xdf

custom.color <- c("#75A8FF", "#FF8076", "#373D3F")

xdf

fig.future.without<- ggplot(xdf, aes(label = disability, values = py, color = disability)) +
  geom_pictogram(n_rows = 10, make_proportional = F, size = picto.size) +
  scale_color_manual( name = NULL, values = custom.color) +
  scale_label_pictogram(name = NULL, values = c(Fruit = "female", Sandwiches = "female", Pizza = "female")) +
  coord_equal() +
  mod.theme + 
  theme(legend.position = "bottom") +
  theme(legend.key.height = unit(0.25, "line")) +
  theme(legend.text = element_text(size = 10, hjust = 0, vjust = .95)) 


fig.future.without
ggsave("/Users/sachinshah/Dropbox/Research - Projects/WIP/future_without.png", fig.future.without, width = 5, height = 5)

````
